name: app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.5 <4.0.0"

dependency_overrides:
  collection: ^1.19.0
  analyzer: 6.2.0
  js: ^0.7.0
  dart_style: 2.3.4


dependencies:
  async: ^2.11.0
  auto_route: ^7.6.0
  cached_network_image: ^3.4.1
  cupertino_icons: 1.0.3
  dartx: ^1.2.0
  domain:
    path: ../domain
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^17.2.4
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.11
  get_it: ^8.0.2
  infinite_scroll_pagination: ^4.0.0
  initializer:
    path: ../initializer
  resources:
    path: ../resources
  shared:
    path: ../shared
  tuple: 2.0.2
dev_dependencies:
  auto_route_generator: 7.1.1
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_gen_runner: ^5.8.0
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.2
  flutter_test:
    sdk: flutter
  freezed: 2.5.2
  freezed_annotation: ^2.4.4
  injectable_generator: ^2.6.2
  logging: ^1.3.0
  mocktail: ^1.0.4
  nals_lints:
    path: ../nals_lints

# Config generate when build
flutter_gen:
  output: lib/resource/generated
  line_lenght: 160
  null_safety: true

  integrations:
    flutter_svg: true
    # flare_flutter: true

  assets:
    enabled: true

  fonts:
    enabled: true
  # colors:
  #   enabled: true
  #   inputs:
  #     - assets/color/colors.xml
flutter:
  uses-material-design: true
  generate: false
  assets:
    - assets/images/
#  fonts:
#    - family: Muli
#      fonts:
#        - asset: assets/fonts/Muli-Bold.ttf
#          weight: 900
#        - asset: assets/fonts/Muli-SemiBold.ttf
#          weight: 700
#        - asset: assets/fonts/Muli-Regular.ttf
#          weight: 400
